You can add CPU (and memory) resource requests and limits within the containers section of your kubernetes-deployment.yaml.

Here's exactly where you can add it, along with an example:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: circle-ci-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: circle-ci-project
  template:
    metadata:
      labels:
        app: circle-ci-project
    spec:
      containers:
        - name: circle-ci-project
          image: us-central1-docker.pkg.dev/sigma-scheduler-461007-u2/circle-ci-project/circle-ci-project:latest
          ports:
            - containerPort: 5000
          resources:             # <--- ADD THIS SECTION
            requests:            # <--- Requests are the minimum guaranteed resources
              cpu: "200m"        # Request 0.2 of a CPU core (200 milli-cores)
              memory: "256Mi"    # Request 256 MiB of memory
            limits:              # <--- Limits are the maximum resources your container can use
              cpu: "500m"        # Limit to 0.5 of a CPU core (500 milli-cores)
              memory: "512Mi"    # Limit to 512 MiB of memory

---
apiVersion: v1
kind: Service
metadata:
  name: circle-ci-project
spec:
  selector:
    app: circle-ci-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
